### ISSUE TITLE
Dependency error: Synthepedia not found

### ISSUE THREAD

**Issue by stefanbringuier** [CederGroupHub/SynthesisSimilarity#1]
I'm unable to satisfy the dependency:

```bash
pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement Synthepedia (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for Synthepedia (from -r requirements.txt (line 1))
```
My virtual environment:

|   Package   | Version |
| --- | --- |
|python|  3.8.10 |
|pip |  20.0.2 |
|pkg-resources | 0.0.0 |  
|setuptools | 44.0.0 |

**Comment by zhugeyicixin** [comment]
Hi Stefan,

The dependency problem has been fixed. Thanks for your patience!

Best,
Tanjin
