### ISSUE TITLE
[Questions:] Question about optional library, Synthepedia and synthesis_dataset

### ISSUE THREAD

**Issue by lichman0405** [CederGroupHub/SynthesisSimilarity#4]
### Email (Optional)

shadow.li981@gmail.com

### Version

v0.1.2

### Which OS(es) are you using?

- [ ] MacOS
- [X] Windows
- [X] Linux

### What happened?

When I tried to install optional packages to use precursorselector for precursor recommendation, I found out that the package named:
1. Synthepedia
2. synthesis_dataset

cannot be found on github or other repositorys. 

Could you please help me with this to lists all optional packages sources?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhugeyicixin** [comment]
Hi @lichman0405, as you may have noticed, Synthepedia and synthesis_dataset are optional because they are for internal use. The precursor recommendation class (e.g. _01_synthesis_recommendation.py) does not actually require these two packages. So please don't worry without them.

**Comment by lichman0405** [comment]
> Hi @lichman0405, as you may have noticed, Synthepedia and synthesis_dataset are optional because they are for internal use. The precursor recommendation class (e.g. _01_synthesis_recommendation.py) does not actually require these two packages. So please don't worry without them.

Big thanks to it. I got it.
